name: Auto Build
run-name: ${{ github.actor }} started auto-build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Create APK
      run: ./gradlew assembleRelease
      
    - name: Rename APK
      run: mv ./app/release/app-release.apk ./DiceApp-autobuild.apk
    
    - name: Build & test
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "autobuild"
          prerelease: true
          title: "Auto Build release."
          files: |
            DiceApp-autobuild.apk
    - name: Clean up
      run: ./gradlew clean :build
    - name: Clean up 2
      run: rm DiceApp-autobuild.apk
