name: Auto Build
run-name: ${{ github.actor }} started auto-build.

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Create APK
      run: ./gradlew assembleDebug
    - name: Rename APK
      run: mv ./app/build/outputs/apk/debug/app-debug.apk ./DiceApp-autobuild.apk
    
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.TOKEN }}"
          automatic_release_tag: "autobuild"
          prerelease: true
          title: "Auto Build release (Experimental)"
          files: |
            DiceApp-autobuild.apk
    - name: Clean
      run: rm DiceApp-autobuild.apk
  clean:
    needs: build
    name: Clean build
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Now clean build
      run: .\gradle.bat clean
