name: Auto Build
run-name: ${{ github.actor }} started auto-build.

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    needs: verify
    name: Start autobuild
    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v3
    - name: set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Give Ubuntu permission
      run: chmod +x gradlew
    - name: Assemble APK
      run: ./gradlew assembleDebug
    - name: Rename APK
      run: mv ./app/build/outputs/apk/debug/app-debug.apk ./DiceApp-autobuild.apk
    - name: Publish release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.TOKEN }}"
          automatic_release_tag: "autobuild"
          prerelease: true
          title: "Auto Build release (Experimental)"
          files: |
            DiceApp-autobuild.apk
  verify:
    name: Verify that build is working
    runs-on: windows-latest

    steps:
    - name: Check out
      uses: actions/checkout@v3
    - name: set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Try to build app
      run: .\gradlew.bat build
