name: Auto Builder
run-name: ${{ github.actor }} started auto-build.

on:
  push:
    paths-ignore:
     - .github/website/
  workflow_dispatch:

jobs:
  build:
    name: Build & Publish
    runs-on: self-hosted
    environment: Autobuild

    steps:
    - uses: actions/checkout@v4.1.5
    - uses: actions/setup-java@v4.2.1
      with:
        java-version: '22'
        distribution: 'temurin'
        cache: gradle
    - name: Prepare (1/2) Allowing permissions
      run: chmod +x gradlew
    - name: Prepare (2/2) Cleaning
      run: ./gradlew clean
    - name: Build
      run: ./gradlew assembleDebug --debug --info --stacktrace
      env:
        ANDROID_HOME: /home/swee/android-sdk
    - name: Stop daemon
      run: ./gradlew --stop
    - name: Moving built APK
      run: mv ./app/build/outputs/apk/debug/app-debug.apk ./DiceApp-autobuild.apk
    - name: Creating checksum
      run: md5sum DiceApp-autobuild.apk > md5sum.md5
    - name: Verifying checksum
      run: md5sum -c md5sum.md5
    - name: Uploading
      uses: Sweeistaken/sweelease@v1.1
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "autobuild"
          prerelease: true
          title: "Auto Build release (Experimental)"
          files: |
            DiceApp-autobuild.apk
            md5sum.md5
