name: Auto Builder
run-name: ${{ github.actor }} started auto-build.

on:
  push:
    paths:
     - app/
     - .github/workflows/build.yml
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    needs: setup
    name: Now building Application
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - run: chmod +x gradlew
    - run: ./gradlew clean
    - run: ./gradlew assembleDebug
    - run: ./gradlew --stop
    - run: mv ./app/build/outputs/apk/debug/app-debug.apk ./DiceApp-autobuild.apk
    - run: md5sum DiceApp-autobuild.apk > md5sum.md5
    - run: md5sum -c md5sum.md5
    - uses: Sweeistaken/sweelease@1.0
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "autobuild"
          prerelease: true
          title: "Auto Build release (Experimental)"
          files: |
            DiceApp-autobuild.apk
            md5sum.md5
  setup:
    runs-on: ubuntu-latest
    name: "setup: Check for required files"

    steps:
    - name: Check out Repository
      uses: actions/checkout@v3
    - name: "'gradlew' for ubuntu"
      run: cat gradlew
    - name: "'graldew.bat' for windows"
      run: cat gradlew.bat
    - name: "Main kotlin file"
      run: cat app/src/main/java/com/pythonanywhere/swee/diceapp/MainActivity.kt
    - name: "Android Manifest"
      run: cat app/src/main/AndroidManifest.xml
