name: Auto Builder
run-name: ${{ github.actor }} started auto-build.

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    needs: setup
    name: Now building Application
    runs-on: ubuntu-latest

    steps:
    - name: Check out Repository
      uses: actions/checkout@v3
    - name: set up Termuin JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Give Ubuntu permission
      run: chmod +x gradlew
    - name: Clean to prevent errors from OneDrive
      run: ./gradlew clean
    - name: Assemble APK
      run: ./gradlew assembleDebug
    - name: Stop daemon
      run: ./gradlew --stop
    - name: Rename APK
      run: mv ./app/build/outputs/apk/debug/app-debug.apk ./DiceApp-autobuild.apk
    - name: Get MD5 of file
      run: md5sum ./DiceApp-autobuild.apk > md5sum.md5
    - name: Check MD5 file
      run: md5sum -c ./md5sum.md5
    - name: Publish release
      uses: Sweeistaken/sweelease@1.0
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "autobuild"
          prerelease: true
          title: "Auto Build release (Experimental)"
          files: |
            DiceApp-autobuild.apk
            md5sum.md5
  setup:
    runs-on: ubuntu-latest
    name: "setup: Check for required files"

    steps:
    - name: Check out Repository
      uses: actions/checkout@v3
    - name: "'gradlew' for ubuntu"
      run: cat gradlew
    - name: "'graldew.bat' for windows"
      run: cat gradlew.bat
    - name: "Main kotlin file"
      run: cat app/src/main/java/com/pythonanywhere/swee/diceapp/MainActivity.kt
    - name: "Android Manifest"
      run: cat app/src/main/AndroidManifest.xml
