name: Auto Builder
run-name: ${{ github.actor }} started auto-build.

on:
  push:
    paths-ignore:
     - .github/website/*
  workflow_dispatch:

jobs:
  build:
    name: Build & Publish
    runs-on: ubuntu-latest
    environment: Autobuild

    steps:
    - uses: actions/checkout@v4.1.5
    - uses: actions/setup-java@v4.2.1
      with:
        java-version: '22'
        distribution: 'temurin'
        cache: gradle
    - name: Allowing permissions
      run: chmod +x gradlew
    - name: Build
      run: ./gradlew clean assembleDebug --debug --info --stacktrace
    - name: Stop daemon
      run: ./gradlew --stop
    - name: Moving built APK
      run: mv ./app/build/outputs/apk/debug/app-debug.apk ./DiceApp-autobuild.apk
    - name: Creating checksum
      run: md5sum DiceApp-autobuild.apk > md5sum.md5
    - name: Verifying checksum
      run: md5sum -c md5sum.md5
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with: 
        name: autobuild
        path: |
          DiceApp-autobuild.apk
          md5sum.md5
        compression-level: 9
